# Configuration du Port (8081 comme vous l'aviez choisi)
server.port=8081
server.error.include-message=always
server.error.include-binding-errors=always

# Base de Données (Vos vrais accès)
spring.datasource.url=jdbc:mysql://localhost:3306/photo_db?serverTimezone=UTC
spring.datasource.username=piconroot
spring.datasource.password=_Picon@2026_
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Sécurité (JWT)
application.security.jwt.secret-key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Dossier de stockage des photos (Sur le serveur Windows, disque F:)
storage.location=F:/uploads
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Configuration des Emails (À Remplacer par les vôtres)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=votre_email@gmail.com
spring.mail.password=votre_mot_de_passe_app_email
spring.mail.properties.mail.smtp.auth=true

# Lien du backend (Domaine de production)
backend.base-url=https://api.photopicon.com
